### ISSUE TITLE
Compilation fails on windows due to assimp-sys

### ISSUE THREAD

**Issue by blooop** [openrr/urdf-viz#14]
cargo install urdf-viz fails on windows while compiling assimp-sys:
```
error: could not find native static library `zlibstatic`, perhaps an -L flag is missing?
error: aborting due to previous error
error: Could not compile `assimp-sys`.
```

I tried installing zlib for windows using this installer:
http://gnuwin32.sourceforge.net/packages/zlib.htm
but that does not fix the issue. 

I found one of your comments about this issue where you found a solution, but I don't think its working any more:
https://github.com/Eljay/assimp-sys/issues/16

Thanks

**Comment by OTL** [comment]
Hi, thank you for trying urdf-viz!

I know that it is difficult to build urdf-viz (assimp-sys) on windows.

At least, on appveyor (windows CI environment), it succeeds.

bellow is the setting for appveyor (I think there are nothing special).
https://github.com/OTL/urdf-viz/blob/master/appveyor.yml

And the log
https://ci.appveyor.com/project/OTL/urdf-viz/builds/19688606

It seems it depends on the environments, and it is difficult to support you for me.

If you solve the problem, please let me know.
