### ISSUE TITLE
feature request: change size of link frame and toggle short cuts menu

### ISSUE THREAD

**Issue by aheadofkym** [openrr/urdf-viz#192]
Hello,

This is a great tool, thank you for making it.

2 feature requests:
Could i request a way to change the size/scale of teh frame axis when on? 
For small parts like single arms, having the link frames on to double check where the joints are, sometimes the link frames are larger then all the parts.

![image](https://user-images.githubusercontent.com/106614301/214156581-17e4082c-3571-4f48-818b-8a8286072e97.png)

Could there be a way to toggle off the shortcuts menu?

Thanks
Kym

**Comment by OTL** [comment]
Hi, nice suggestion!
I completely understand the first request. I'll do it soon.

> Could there be a way to toggle off the shortcuts menu?

Do you mean that you want to remove the text on the screen?

**Comment by kaaatsu32329** [comment]
@aheadofkym
Thank you for nice suggestions! I updated `urdf-viz` to implement requiested features. How do you like the added features in this PR (#194)?

**Comment by aheadofkym** [comment]
@kaaatsu32329 , thats fantastic, thankyou.
