### ISSUE TITLE
thread 'main' panicked at 'failed to execute xacro. [...]'

### ISSUE THREAD

**Issue by suuppl** [openrr/urdf-viz#31]
Hi,
apparently, urdf-viz can't find xacro.
I reinstalled xacro and sourced all necessary files.
I am on Ubuntu 16.04, ROS Kinetic.

Backtrace:
`thread 'main' panicked at 'failed to execute xacro. install by apt-get install ros-*-xacro: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/seppl/.cargo/registry/src/github.com-1ecc6299db9ec823/urdf-rs-0.4.2/src/utils.rs:14:18
stack backtrace:
   0:     0x55badf13a5e4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55badf13a5e4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55badf13a5e4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55badf13a5e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55badf15fe6c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55badf133df7 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x55badf13c805 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55badf13c805 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55badf13c805 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x55badf13c4f1 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x55badf13ce6a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x55badf13ca50 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55badf15dd31 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x55badf15db53 - core::option::expect_none_failed::he6711468044f7162
                               at src/libcore/option.rs:1199
  14:     0x55bade93b8c4 - urdf_rs::utils::read_urdf_or_xacro::heb972548146e4274
  15:     0x55bade92ba62 - urdf_viz::main::hd543a08e4c4baece
  16:     0x55bade92e7c3 - std::rt::lang_start::{{closure}}::h9c83dbf064a9a08c
  17:     0x55badf13c933 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  18:     0x55badf13c933 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  19:     0x55badf145d67 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:     0x55badf13d3d0 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  21:     0x55badf13d3d0 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  22:     0x55badf13d3d0 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  23:     0x55bade92e682 - main
  24:     0x7f28502d8830 - __libc_start_main
  25:     0x55bade91fe79 - _start
  26:                0x0 - <unknown>
`

**Comment by OTL** [comment]
urdf_rs uses "xacro" without rosrun. You need to set PATH to xacro.
In your case, /opt/ros/kinetic/bin. I think you should have the PATH in your env.
Please source setup.bash before run urdf-viz.
