### ISSUE TITLE
Reset robot pose by z key.

### ISSUE THREAD

**Issue by OTL** [openrr/urdf-viz#43]
urdf supports moving the robot by http request.
But it is not possible to reset by key short cut.
I want to support it by `z` key.

As a work around, it can be done by `l` key (reload urdf).

**Comment by taiki-e** [comment]
IIUC, this seems to be already supported.
https://github.com/openrr/urdf-viz/blob/322cf923f7171392ebbeebd51787d4b10e2774be/src/bin/urdf-viz.rs#L96
https://github.com/openrr/urdf-viz/blob/322cf923f7171392ebbeebd51787d4b10e2774be/src/bin/urdf-viz.rs#L356-L361
